import type { Experience } from "@/lib/types";

export const experience: Experience[] = [
  {
    slug: "world-bank",
    role: "Project Engineer Consultant",
    company: "World Bank",
    period: "2014",
    location: "Bandung, Indonesia",
    description:
      "Modeled carbon capture for Indonesian power plants.",
    highlights: ["CCUS at 90%+ efficiency"],
    tags: ["CCUS", "TEA", "Process Simulation"],
    logo: "/logos/worldbank.svg",
  },
  {
    slug: "dow-sales",
    role: "Account Manager",
    company: "Dow",
    period: "2015 — 2016",
    location: "Jakarta, Indonesia",
    description: "Launched sustainable adhesives across South East Asia.",
    highlights: ["$4M+ revenue growth"],
    tags: ["Sales", "Go-to-Market", "B2B"],
    logo: "/logos/dow.svg",
  },
  {
    slug: "icon-consultant",
    role: "Consultant",
    company: "ICON",
    period: "2016 — 2017",
    location: "Stockholm, Sweden",
    description: "Strategy consulting for tech startups and scale-ups.",
    highlights: [
      "$5M+ fiber optic profit",
      "60% urban emissions cut modeled",
    ],
    tags: ["Strategy", "Market Entry", "Due Diligence"],
    logo: "/logos/icon.svg",
  },
  {
    slug: "kth-researcher",
    role: "Project Researcher",
    company: "KTH Royal Institute",
    period: "2017 — 2018",
    location: "Stockholm, Sweden",
    description:
      "Researched supermarket refrigeration energy efficiency.",
    highlights: [
      "Heat recovery to district heating",
      "Published at HVAC conference",
    ],
    tags: ["HVAC", "District Heating"],
    logo: "/logos/kth.svg",
  },
  {
    slug: "edf-intern",
    role: "R&D Engineer Intern",
    company: "EDF",
    period: "2018",
    location: "Paris, France",
    description: "Master's thesis at EDF Lab Chatou on emerging energy tech.",
    highlights: ["−40% R&D cycles", "50+ technologies evaluated"],
    tags: ["TEA", "Waste-to-Energy", "TRL"],
    logo: "/logos/edf.svg",
  },
  {
    slug: "wienerberger-lca",
    role: "Sustainability Data Analyst & LCA Consultant",
    company: "Wienerberger",
    period: "2021 — 2022",
    location: "Leuven, Belgium",
    description: "LCA consulting on waste-derived building materials.",
    highlights: [
      "10–30% carbon reduction",
      "Published in J. Cleaner Production",
    ],
    tags: ["LCA", "Carbon Accounting"],
    logo: "/logos/wienerberger.svg",
  },
  {
    slug: "eth-empa-lead-researcher",
    role: "Lead Researcher",
    company: "ETH Zürich & Empa",
    period: "2019 — 2023",
    location: "Zürich, Switzerland",
    description: "Led environmental data modeling for the ICT sector.",
    highlights: ["+30% data transparency", "Cited in UN GRO 2024"],
    tags: ["LCA", "Data Modeling", "UN GRO 2024"],
    logo: "/logos/eth.svg",
  },
  {
    slug: "siemens",
    role: "Sustainability Program Manager & PM",
    company: "Siemens",
    period: "2023 — Now",
    location: "Zug, Switzerland",
    description: "Cross-functional sustainability and product programs.",
    highlights: [
      "+50% eco-design adoption",
      "+20% Scope 3 cut",
      "+5M EUR SaaS revenue",
    ],
    tags: ["Product", "Scope 3", "Ecodesign", "GenAI"],
    logo: "/logos/siemens.svg",
  },
];
